// ============================================================
// Resend email helper — transactional audit confirmation emails
// ============================================================

import { Resend } from 'resend';
import type { AuditResult } from '@/types/audit';

let resendClient: Resend | null = null;

function getClient(): Resend | null {
  if (!process.env.RESEND_API_KEY) {
    console.warn('[Resend] Missing API key — emails will be logged to console');
    return null;
  }
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

interface SendAuditEmailParams {
  to: string;
  audit: AuditResult;
  companyName?: string;
}

export async function sendAuditConfirmationEmail({
  to,
  audit,
  companyName,
}: SendAuditEmailParams): Promise<boolean> {
  const client = getClient();
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

  const subject = `Your AI Spend Audit — Save $${audit.totalMonthlySavings}/month`;

  const html = buildEmailHtml(audit, companyName, appUrl);

  if (!client) {
    console.log('[Resend Mock] Would send email to:', to);
    console.log('[Resend Mock] Subject:', subject);
    return true;
  }

  try {
    await client.emails.send({
      from: `AI Spend Audit <${fromEmail}>`,
      to: [to],
      subject,
      html,
    });
    return true;
  } catch (error) {
    console.error('[Resend] Failed to send email:', error);
    return false;
  }
}

function buildEmailHtml(
  audit: AuditResult,
  companyName: string | undefined,
  appUrl: string
): string {
  const greeting = companyName ? `Hi ${companyName} team` : 'Hi there';
  const shareUrl = `${appUrl}/results/${audit.id}`;

  const recsHtml = audit.recommendations
    .slice(0, 5)
    .map(
      (r) => `
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb;">${r.toolName}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb;">${r.recommendedAction}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #e5e7eb; color: #10b981; font-weight: 600;">$${r.monthlySavings}/mo</td>
      </tr>`
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #1f2937;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 24px; font-weight: 700; margin: 0;">AI Spend Audit</h1>
        <p style="color: #6b7280; margin: 4px 0 0;">by Credex</p>
      </div>

      <p>${greeting},</p>
      <p>Here's your AI spend audit summary:</p>

      <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); border-radius: 12px; padding: 24px; text-align: center; color: white; margin: 20px 0;">
        <p style="margin: 0; font-size: 14px; opacity: 0.9;">Potential Monthly Savings</p>
        <p style="margin: 4px 0 0; font-size: 36px; font-weight: 800;">$${audit.totalMonthlySavings}</p>
        <p style="margin: 4px 0 0; font-size: 14px; opacity: 0.9;">$${audit.totalAnnualSavings}/year</p>
      </div>

      ${audit.aiSummary ? `<p style="background: #f9fafb; border-radius: 8px; padding: 16px; border-left: 4px solid #10b981;">${audit.aiSummary}</p>` : ''}

      <table style="width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px;">
        <thead>
          <tr style="background: #f9fafb;">
            <th style="padding: 8px 12px; text-align: left;">Tool</th>
            <th style="padding: 8px 12px; text-align: left;">Recommendation</th>
            <th style="padding: 8px 12px; text-align: left;">Savings</th>
          </tr>
        </thead>
        <tbody>${recsHtml}</tbody>
      </table>

      <div style="text-align: center; margin: 24px 0;">
        <a href="${shareUrl}" style="background: #10b981; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600;">View Full Report</a>
      </div>

      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;">

      <p style="font-size: 12px; color: #9ca3af; text-align: center;">
        This audit was generated by <a href="${appUrl}" style="color: #10b981;">AI Spend Audit</a> by Credex.
        Want enterprise-level savings? <a href="https://credex.com" style="color: #10b981;">Talk to us</a>.
      </p>
    </body>
    </html>
  `;
}
